version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Porta usada pelas aplicações para enviar/receber mensagens
      - "15672:15672" # Interface Web (RabbitMQ Management UI)
    environment:
      RABBITMQ_DEFAULT_USER: meuusuario
      RABBITMQ_DEFAULT_PASS: senhasecreta
      RABBITMQ_DEFAULT_VHOST: meuvhost
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
